name: CI

on:
  push:
    branches: "master"
  pull_request:
    branches: "*"

jobs:

  build:
    name: ubuntu-latest ${{ matrix.config.go_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - go_version: 1.13
          - go_version: 1.14
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.config.go_version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install goimports
      run: go get golang.org/x/tools/cmd/goimports

    - name: Install go ci lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0

    - name: Test
      run: |
        diff -u <(echo -n) <(gofmt -d -s .)
        diff -u <(echo -n) <(goimports -d .)
        golangci-lint run -v --disable-all --enable=govet --enable=staticcheck --enable=ineffassign --enable=misspell
        go test -v -race ./... -coverprofile=coverage.txt -covermode=atomic

    - name: Coverage
      run: bash <(curl -s https://codecov.io/bash)
